name: Testing PrestaShop pull requests
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: Pull request to test
        required: true
      base_branch:
        description: Base branch to rebase the PR
        required: true
        default: 'develop'
      php_version:
        description: PHP version
        required: true
        default: '7.3'

jobs:
  testing-pr:
    runs-on: ubuntu-latest
    name: test
    strategy:
      fail-fast: false
      matrix:
        TEST_COMMAND:
          - 'functional:BO:login'

    env:
      PR_NUMBER: ${{ github.event.inputs.pr_number }}
      BASE_BRANCH: ${{ github.event.inputs.base_branch }}
      PHP_VERSION: ${{ github.event.inputs.php_version }}
      PS_DIR: 'my_prestashop'

    steps:
      - uses: actions/checkout@v2
        with:
          path: main

      - uses: actions/checkout@v2
        name: Checkout PrestaShop repository
        with:
          fetch-depth: 2
          repository: PrestaShop/PrestaShop
          path: ${{ env.PS_DIR }}

      - name: Get pull request
        run: |
          git fetch origin pull/${{ env.PR_NUMBER }}/head:pr${{ env.PR_NUMBER }}
          git checkout pr${{ env.PR_NUMBER }}
        working-directory: ${{ env.PS_DIR }}

      - name: Setup Apache
        run: sudo bash scripts/apache/setup.sh ${{ github.workspace }} ${{ env.PS_DIR }} ${{ env.PHP_VERSION }}
        working-directory: main

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv, simplexml, pdo, mysql

      # temporary fix to make latest 7.4 & 8.0 work
      - name: Update PCRE2
        run: sudo apt-get install -y libpcre2-dev

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '5.7'
          mysql database: 'prestashop'
          mysql root password: 'password'

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: PrestaShop Configuration
        run: cp scripts/php/parameters.yml ${{ env.PS_DIR }}/app/config/parameters.yml

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache node Directory
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Cache Composer Directory
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Composer install and build assets
        run: make
        working-directory: ${{ env.PS_DIR }}

      - name: Install PrestaShop
        run: php install-dev/index_cli.php --language=en --country=fr --domain=localhost --db_server=127.0.0.1 --db_password=password --db_name=prestashop --db_create=1 --firstname="Marc" --lastname="Beier" --email=demo@prestashop.com --password=prestashop_demo
        working-directory: ${{ env.PS_DIR }}

      - run: |
          sudo chmod 777 -R ${{ github.workspace }}
          sudo mkdir -p /var/lib/php/sessions
          sudo chown www-data:www-data /var/lib/php/sessions
          sudo service apache2 restart
          sudo ls -l ${{ env.PS_DIR }}

      - name: Install tests dependencies
        run: npm install
        working-directory: '${{ env.PS_DIR }}/tests/UI'

      - name: Run tests
        run: npm run test:${{ matrix.TEST_COMMAND }}
        working-directory: '${{ env.PS_DIR }}/tests/UI'
        env:
          URL_FO: http://localhost/
          DB_NAME: prestashop
          DB_PASSWD: password
          HEADLESS: true
          TAKE_SCREENSHOT_AFTER_FAIL: true

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: screenshots
          path: '${{ env.PS_DIR }}/tests/UI/screenshots/'
